### ISSUE TITLE
Unable to load extension "BanId_Fix.ext": Failed to get Filter_IsUserBanned signature.

### ISSUE THREAD

**Issue by 8guawong** [komashchenko/BanId_Fix#4]
L 10/22/2022 - 07:05:35: [SM] Unable to load extension "BanId_Fix.ext": Failed to get Filter_IsUserBanned signature.

After today's csgo update

On Windows

**Comment by komashchenko** [comment]
Fixed since now it's a plugin don't forget to delete the old extension files
