### ISSUE TITLE
Gamedata broken

### ISSUE THREAD

**Issue by asdfxD** [komashchenko/BanId_Fix#5]
Hi,

gamedata seems to be broken in linux after the latest csgo update.

**Comment by data-bomb** [comment]
engine signature for Filter_IsUserBanned has changed. i'll submit a PR

**Comment by data-bomb** [comment]
@asdfxD could you check if the gamedata in https://github.com/komashchenko/BanId_Fix/pull/6 addresses your issue on linux?

**Comment by Mikasan15** [comment]
L 02/04/2023 - 10:51:36: [SM] Exception reported: Failed to create call for Filter_Steam64bitIdToUserID
L 02/04/2023 - 10:51:36: [SM] Blaming: BanId_Fix.smx
L 02/04/2023 - 10:51:36: [SM] Call stack trace:
L 02/04/2023 - 10:51:36: [SM]   [0] SetFailState
L 02/04/2023 - 10:51:36: [SM]   [1] Line 68, BanId_Fix.sp::OnPluginStart
L 02/04/2023 - 10:51:36: [SM] Unable to load plugin "BanId_Fix.smx": Error detected in plugin startup (see error logs)

**Comment by asdfxD** [comment]
@data-bomb plugin seems to be working fine with new gamedata, i don't have these errors above.
